### PR TITLE
Iteration 4

### PR DESCRIPTION
**Pull request by aliciatay-zls**
Complete to-do list by mentor:
- [ ] Add ability to limit search results to user's chosen radius of distance
- [x] Ensure user's search is only either by brand or category
- [x] Modify MySQL queries in rest_api.js to use `categories` and `brand_categories` tables
- [ ] Improve user's readability of distances displayed
- [x] Add new sample data: McDonald’s
- [x] Refactor code for rest_api.js
- [x] Remove need for intermediary .csv files when importing data to db

### CODE REVIEW

**Comment by miccheng** [comment]
Something for you to consider: Is there a more direct way of getting the outlet and brand info into the DB tables?

**Comment by aliciatay-zls** [comment]
> Something for you to consider: Is there a more direct way of getting the outlet and brand info into the DB tables?

Thanks Mr Cheng, I have added it as a task to the to-do list.

**Comment by aliciatay-zls** [comment]
Commit https://github.com/aliciatay-zls/NearMe/pull/3/commits/ced6823d3d1f1e1ac476a07b4076b9cc7688ddc7 : for completeness' sake. Changing implementation going forward.

**Comment by aliciatay-zls** [comment]
Commits ced6823, f5f18a2: for completeness' sake. Changing implementation going forward.

**Review by miccheng — APPROVED** [review]
LGTM

**Pull request merged**
